# Непрерывные случайные величины. Функция распределения и функция плотности. Нормальное распределение. Центральная предельная теорема

In [10]:
from scipy import integrate
from math import pi
from math import exp
from math import sqrt

#### 1. Случайная непрерывная величина A имеет равномерное распределение на промежутке (200, 800]. Найдите ее среднее значение и дисперсию.


In [1]:
a = 200
b = 800

In [2]:
m = (a + b) / 2
d = (b - a)**2 / 12
print(f"Среднее значение: {m}")
print(f"Дисперсия: {d}")

Среднее значение: 500.0
Дисперсия: 30000.0


#### 2. О случайной непрерывной равномерно распределенной величине B известно, что ее дисперсия равна 0.2. Можно ли найти правую границу величины B и ее среднее значение зная, что левая граница равна 0.5? Если да, найдите ее.


Зная формулу диспресии для равномерно распределенной случайной величины можно вычислить правую границу (a), зная ее диспрерсию и левую границу (b):
##### d = (b - a)**2 / 12

In [19]:
d = 0.2
b = 0.5

Считаем уравнение: (0.2 = (0.5 - a)^2)/12 (Решение пропустим....) и получаем 2 корня:

In [20]:
a1 = -1.05
a2 = 2.05

В результате решения квадратного уравнения получается, один из которых отрицательный и не подходит на роль правой границы, т.к. правая граница должна быть больше левой.

In [22]:
m = (b + a2) / 2
print(f"Правая граница {a2}, Среднее значение {m}")

Правая граница 2.05, Среднее значение 1.275


#### 3. Непрерывная случайная величина X распределена нормально и задана плотностью распределения f(x) = (1 / (4 * sqrt(2*pi))) * (exp(-(x+2)**2) / 32). Найдите: а). M(X) б). D(X) в). std(X) (среднее квадратичное отклонение)


In [23]:
#Из сопоставления функции плотности выводится легко. 
d = 16
m = -2
std = 4
print(f"D(X):{d}, М(X):{m}, std(X):{std}")

D(X):16, М(X):-2, std(X):4


#### 4. Рост взрослого населения города X имеет нормальное распределение. Причем, средний рост равен 174 см, а среднее квадратичное отклонение равно 8 см. Какова вероятность того, что случайным образом выбранный взрослый человек имеет рост:

а). больше 182 см

б). больше 190 см

в). от 166 см до 190 см

г). от 166 см до 182 см

д). от 158 см до 190 см

е). не выше 150 см или не ниже 190 см

ё). не выше 150 см или не ниже 198 см

ж). ниже 166 см.


Для начала необходимо нормировать случайную величину

In [2]:
def Z(x):
    return (x - 174) / 8
    

In [20]:
z_150 = Z(150)
print(f"z_150:{z_150}")
z_158 = Z(158)
print(f"z_158:{z_158}")
z_166 = Z(166)
print(f"z_166:{z_166}")
z_182 = Z(182)
print(f"z_182:{z_182}")
z_190 = Z(190)
print(f"z_190:{z_190}")
z_198 = Z(198)
print(F"z_198:{z_198}")

z_150:-3.0
z_158:-2.0
z_166:-1.0
z_182:1.0
z_190:2.0
z_198:3.0


Подберем вероятности по таблице Z-значений

а). больше 182 см

In [29]:
p_182 = 0.15866 * 100
print(f"P(>182): {p_182}%")

P(>182): 15.866%


б). больше 190 см

In [22]:
p_190 = 0.02275 * 100
print(f"P(>190): {p_190}%")

P(>190): 2.275%


в). от 166 см до 190 см

In [23]:
p_166 = 0.1587 * 100
p_190 = 0.9772 * 100
print(f"P(166<x<190): {p_190 - p_166}%")

P(166<x<190): 81.85%


г). от 166 см до 182 см

In [24]:
p_166 = 0.1587 * 100
p_182 = 0.8413 * 100
print(f"P(166<x<182): {p_182 - p_166}%")

P(166<x<182): 68.26%


д). от 158 см до 190 см

In [31]:
p_158 = 0.0228 * 100
p_190 = 0.9772 * 100
print(f"P(158<x<190): {p_190 - p_158}%")

P(158<x<190): 95.44%


е). не выше 150 см или не ниже 190 см

In [33]:
p_150= 0.0013 * 100
p_190 = 0.02275 * 100
print(f"P(150<x || x > 190): { p_150 + p_190}%")

P(150<x || x > 190): 2.405%


ё). не выше 150 см или не ниже 198 см

In [34]:
p_150= 0.0013 * 100
p_198 = 0.00135 * 100
print(f"P(150<x || x > 198): {p_150 + p_198}%")

P(150<x || x > 198): 0.265%


ж). ниже 166 см.

In [28]:
p_166 = 0.1587 * 100
print(f"P(<166): {p_166}%")

P(<166): 15.870000000000001%


#### 5. На сколько сигм (средних квадратичных отклонений) отклоняется рост человека, равный 190 см, от математического ожидания роста в популяции, в которой M(X) = 178 см и D(X) = 25 кв.см?


In [5]:
m = 178
d = 25
x = 190

In [7]:
z = (x - m) / d**(1/2)
print(f"Рост человека {x}см ,будет отклонятся от роста {m}см на {z} сигмы")

Рост человека 190см ,будет отклонятся от роста 178см на 2.4 сигмы
